# Generated by Django 5.1.7 on 2025-07-17 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='registration_number',
            field=models.CharField(blank=True, max_length=30, null=True, unique=True),
        ),
    ]
