# Generated by Django 5.1.7 on 2025-07-24 09:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_profile_registration_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='session',
            field=models.ForeignKey(default=7, on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to='dashboard.classsession'),
            preserve_default=False,
        ),
    ]
